pool: Defualt

trigger:
 branches:
   include:
     - main
     - feature/*
 paths:
   include:
     - environment/dev

variables:
  - group: dhondu
  - name: STORAGE_ACCOUNT_NAME
    value: 'tfstatestgname'
  - name: WORK_DIR
    value: '$(System.DefaultWorkingDirectory)/environments\dev'
  - name: SERVICE_CONNECTION
    value: 'azure-sc'

stages:
  - stage: PreCommit
    displayName: Pre-Commit / Static Analysis Stage
    pool: Default
    jobs:
      - job: TerraformValidate
        displayName: Terraform Validate
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(WORK_DIR)'
            backendServiceArm: '$(SERVICE_CONNECTION)'
            backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT_NAME)'
            backendAzureRmContainerName: 'tfstates'
            backendAzureRmKey: 'dev.terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(WORK_DIR)'
      - job: TerraformFmt
        dependsOn: TerraformValidate
        displayName: Terraform Fmt
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(WORK_DIR)'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'
      - job: tfsec
        dependsOn: TerraformFmt
        displayName: Tfsec Scan
        steps:
        

